generatorName: python
outputDir: ./out
globalProperties:
  skipFormModel: true
additionalProperties:
  packageName: nocturne_py
  projectName: nocturne-py
  packageVersion: "0.1.0"
  packageUrl: https://github.com/nightscout/nocturne
  licenseName: AGPL-3.0-only
