generatorName: typescript-fetch
outputDir: ./out
globalProperties:
  skipFormModel: true
additionalProperties:
  npmName: "@nightscoutfoundation/nocturne"
  npmVersion: "0.1.0"
  gitUserId: "nightscout"
  gitRepoId: "nocturne"
  supportsES6: true
  typescriptThreePlus: true
  withInterfaces: true
  useSingleRequestParameter: false
  prefixParameterInterfaces: true
  licenseName: AGPL-3.0-only
  modelPropertyNaming: original
