import type { ComponentType } from "svelte";
import {
	Activity,
	Apple,
	BarChart3,
	Battery,
	Bell,
	BellRing,
	Building,
	Calendar,
	CalendarDays,
	ChartArea,
	ChartCandlestick,
	ChartColumnIncreasing,
	ChartLine,
	CirclePlus,
	ClipboardList,
	Clock,
	Cpu,
	Database,
	Droplet,
	FileSearch,
	FileText,
	Footprints,
	Heart,
	House,
	LifeBuoy,
	Link,
	Lock,
	MapPin,
	Moon,
	Palette,
	Pill,
	Plug,
	Plus,
	RefreshCw,
	Ruler,
	Shield,
	Stethoscope,
	Sun,
	Syringe,
	Target,
	Timer,
	TrendingUp,
	TriangleAlert,
	User,
	Users,
	UtensilsCrossed,
	Wrench,
	ZoomIn,
} from "lucide-svelte";

export type CommandPaletteGroup =
	| "stats"
	| "reports"
	| "pages"
	| "settings"
	| "quick-settings"
	| "actions";

export interface CommandPaletteItem {
	id: string;
	label: string;
	group: CommandPaletteGroup;
	description?: string;
	keywords?: string[];
	icon?: ComponentType;
	shortcut?: string;
	permission?: string;
	href?: string;
	linkedHref?: string;
}

export const groupMeta: Record<CommandPaletteGroup, { label: string; order: number }> = {
	stats: { label: "Stats", order: 0 },
	reports: { label: "Reports", order: 1 },
	pages: { label: "Pages", order: 2 },
	settings: { label: "Settings", order: 3 },
	"quick-settings": { label: "Quick Settings", order: 4 },
	actions: { label: "Actions", order: 5 },
};

export const items: CommandPaletteItem[] = [
	// ─── Stats ───────────────────────────────────────────────────────────
	{
		id: "stat-iob",
		label: "IOB",
		group: "stats",
		description: "Insulin on board",
		keywords: ["insulin on board", "active insulin"],
		icon: Droplet,
		linkedHref: "/reports/insulin-delivery",
	},
	{
		id: "stat-cob",
		label: "COB",
		group: "stats",
		description: "Carbs on board",
		keywords: ["carbs on board", "active carbs"],
		icon: Pill,
		linkedHref: "/reports/treatments",
	},
	{
		id: "stat-cage",
		label: "CAGE",
		group: "stats",
		description: "Cannula age",
		keywords: ["cannula age", "infusion set", "site age"],
		icon: Timer,
		linkedHref: "/reports/site-change-impact",
	},
	{
		id: "stat-sage",
		label: "SAGE",
		group: "stats",
		description: "Sensor age",
		keywords: ["sensor age", "cgm age"],
		icon: Cpu,
		linkedHref: "/reports/data-quality",
	},
	{
		id: "stat-a1c",
		label: "eHbA1c",
		group: "stats",
		description: "Estimated HbA1c",
		keywords: ["estimated a1c", "hba1c", "glycated hemoglobin"],
		icon: Activity,
		linkedHref: "/reports/executive-summary",
	},
	{
		id: "stat-tir",
		label: "TIR",
		group: "stats",
		description: "Time in range",
		keywords: ["time in range", "in range", "percentage"],
		icon: Target,
		linkedHref: "/reports/agp",
	},

	// ─── Reports ─────────────────────────────────────────────────────────
	{
		id: "report-agp",
		label: "AGP",
		group: "reports",
		description: "Ambulatory Glucose Profile",
		keywords: ["ambulatory glucose profile", "glucose profile", "percentiles", "target range"],
		icon: ChartArea,
		href: "/reports/agp",
	},
	{
		id: "report-glucose-distribution",
		label: "Glucose Distribution",
		group: "reports",
		description: "Box plot analysis of glucose values",
		keywords: ["box chart", "box plot", "whisker", "percentiles", "quartiles", "spread"],
		icon: ChartCandlestick,
		href: "/reports/glucose-distribution",
	},
	{
		id: "report-executive-summary",
		label: "Executive Summary",
		group: "reports",
		description: "High-level overview of glucose management",
		keywords: ["overview", "summary", "report card", "snapshot"],
		icon: ClipboardList,
		href: "/reports/executive-summary",
	},
	{
		id: "report-day-in-review",
		label: "Day in Review",
		group: "reports",
		description: "Detailed daily glucose review",
		keywords: ["daily", "today", "yesterday"],
		icon: Calendar,
		href: "/reports/day-in-review",
	},
	{
		id: "report-week-to-week",
		label: "Week to Week",
		group: "reports",
		description: "Weekly comparison of glucose data",
		keywords: ["comparison", "trend", "weekly"],
		icon: TrendingUp,
		href: "/reports/week-to-week",
	},
	{
		id: "report-month-to-month",
		label: "Month to Month",
		group: "reports",
		description: "Monthly comparison of glucose data",
		keywords: ["comparison", "trend", "monthly"],
		icon: CalendarDays,
		href: "/reports/month-to-month",
	},
	{
		id: "report-year-overview",
		label: "Year Overview",
		group: "reports",
		description: "Annual glucose summary",
		keywords: ["annual", "yearly", "12 month"],
		icon: BarChart3,
		href: "/reports/year-overview",
	},
	{
		id: "report-treatments",
		label: "Treatments",
		group: "reports",
		description: "Treatment event log and analysis",
		keywords: ["bolus", "carbs", "corrections", "insulin"],
		icon: Syringe,
		href: "/reports/treatments",
	},
	{
		id: "report-insulin-delivery",
		label: "Insulin Delivery",
		group: "reports",
		description: "Total daily dose and basal/bolus breakdown",
		keywords: ["tdd", "total daily dose", "basal bolus ratio"],
		icon: ChartColumnIncreasing,
		href: "/reports/insulin-delivery",
	},
	{
		id: "report-idp",
		label: "IDP",
		group: "reports",
		description: "Insulin Dose Per analysis",
		keywords: ["insulin dose per", "daily insulin", "dose adjustment"],
		icon: ChartLine,
		href: "/reports/idp",
	},
	{
		id: "report-basal-analysis",
		label: "Basal Analysis",
		group: "reports",
		description: "Basal rate patterns and adjustments",
		keywords: ["basal rate", "background insulin", "temp basal"],
		icon: Activity,
		href: "/reports/basal-analysis",
	},
	{
		id: "report-readings",
		label: "Readings",
		group: "reports",
		description: "Glucose readings log",
		keywords: ["glucose readings", "blood sugar", "log", "history"],
		icon: FileText,
		href: "/reports/readings",
	},
	{
		id: "report-sleep",
		label: "Sleep",
		group: "reports",
		description: "Overnight glucose analysis",
		keywords: ["overnight", "night time", "sleeping"],
		icon: Moon,
		href: "/reports/sleep",
	},
	{
		id: "report-steps",
		label: "Steps",
		group: "reports",
		description: "Step count and activity tracking",
		keywords: ["activity", "walking", "exercise", "movement"],
		icon: Footprints,
		href: "/reports/steps",
	},
	{
		id: "report-heart-rate",
		label: "Heart Rate",
		group: "reports",
		description: "Heart rate trends and zones",
		keywords: ["pulse", "bpm", "cardio"],
		icon: Heart,
		href: "/reports/heart-rate",
	},
	{
		id: "report-battery",
		label: "Battery",
		group: "reports",
		description: "Device battery level history",
		keywords: ["pump battery", "phone battery", "charge"],
		icon: Battery,
		href: "/reports/battery",
	},
	{
		id: "report-site-change-impact",
		label: "Site Change Impact",
		group: "reports",
		description: "Glucose impact around infusion site changes",
		keywords: ["infusion site", "cannula", "rotation", "set change"],
		icon: MapPin,
		href: "/reports/site-change-impact",
	},
	{
		id: "report-data-quality",
		label: "Data Quality",
		group: "reports",
		description: "Data coverage and gap analysis",
		keywords: ["gaps", "missing", "coverage", "reliability"],
		icon: Database,
		href: "/reports/data-quality",
	},

	// ─── Pages ───────────────────────────────────────────────────────────
	{
		id: "page-dashboard",
		label: "Dashboard",
		group: "pages",
		keywords: ["home", "main", "overview"],
		icon: House,
		href: "/",
	},
	{
		id: "page-food",
		label: "Food",
		group: "pages",
		keywords: ["food", "nutrition", "carbs"],
		icon: Apple,
		href: "/food",
	},
	{
		id: "page-meals",
		label: "Meals",
		group: "pages",
		keywords: ["meals", "eating", "dining"],
		icon: UtensilsCrossed,
		href: "/meals",
	},
	{
		id: "page-calendar",
		label: "Calendar",
		group: "pages",
		keywords: ["calendar", "schedule", "dates"],
		icon: CalendarDays,
		href: "/calendar",
	},
	{
		id: "page-tools",
		label: "Tools",
		group: "pages",
		keywords: ["tools", "utilities"],
		icon: Wrench,
		href: "/tools",
	},
	{
		id: "page-notifications",
		label: "Notifications",
		group: "pages",
		keywords: ["notifications", "alerts", "messages"],
		icon: Bell,
		href: "/notifications",
	},
	{
		id: "page-time-spans",
		label: "Time Spans",
		group: "pages",
		keywords: ["time spans", "ranges", "periods"],
		icon: Clock,
		href: "/time-spans",
	},
	{
		id: "page-tenants",
		label: "Tenants",
		group: "pages",
		keywords: ["tenants", "organizations", "accounts"],
		icon: Building,
		href: "/tenants",
		permission: "api:tenants:read",
	},

	// ─── Settings ────────────────────────────────────────────────────────
	{
		id: "settings-account",
		label: "Account",
		group: "settings",
		keywords: ["account", "email", "password"],
		icon: User,
		href: "/settings/account",
	},
	{
		id: "settings-profile",
		label: "Profile",
		group: "settings",
		keywords: ["profile", "name", "avatar"],
		icon: User,
		href: "/settings/profile",
	},
	{
		id: "settings-appearance",
		label: "Appearance",
		group: "settings",
		keywords: ["appearance", "theme", "dark mode", "light mode"],
		icon: Palette,
		href: "/settings/appearance",
	},
	{
		id: "settings-alarms",
		label: "Alarms",
		group: "settings",
		keywords: ["alarms", "urgent", "glucose alerts"],
		icon: BellRing,
		href: "/settings/alarms",
	},
	{
		id: "settings-alerts",
		label: "Alerts",
		group: "settings",
		keywords: ["alerts", "warnings", "notifications"],
		icon: TriangleAlert,
		href: "/alerts",
	},
	{
		id: "settings-grants",
		label: "Grants",
		group: "settings",
		keywords: ["grants", "access", "permissions", "sharing"],
		icon: Shield,
		href: "/settings/grants",
		permission: "api:settings:admin",
	},
	{
		id: "settings-connectors",
		label: "Connectors",
		group: "settings",
		keywords: ["connectors", "dexcom", "libre", "glooko"],
		icon: Plug,
		href: "/settings/connectors",
	},
	{
		id: "settings-integrations",
		label: "Integrations",
		group: "settings",
		keywords: ["integrations", "api", "webhooks"],
		icon: Link,
		href: "/settings/integrations",
	},
	{
		id: "settings-data-quality",
		label: "Data Quality",
		group: "settings",
		keywords: ["data quality", "gaps", "thresholds"],
		icon: Shield,
		href: "/settings/data-quality",
	},
	{
		id: "settings-therapy",
		label: "Therapy",
		group: "settings",
		keywords: ["therapy", "treatment", "insulin type"],
		icon: Stethoscope,
		href: "/settings/therapy",
	},
	{
		id: "settings-patient",
		label: "Patient",
		group: "settings",
		keywords: ["patient", "demographic", "details"],
		icon: User,
		href: "/settings/patient",
	},
	{
		id: "settings-sharing",
		label: "Sharing",
		group: "settings",
		keywords: ["sharing", "followers", "caregivers"],
		icon: Users,
		href: "/settings/sharing",
	},
	{
		id: "settings-members",
		label: "Members",
		group: "settings",
		keywords: ["members", "users", "team"],
		icon: Users,
		href: "/settings/members",
		permission: "api:settings:admin",
	},
	{
		id: "settings-roles",
		label: "Roles",
		group: "settings",
		keywords: ["roles", "permissions", "access control"],
		icon: Lock,
		href: "/settings/roles",
		permission: "api:settings:admin",
	},
	{
		id: "settings-audit",
		label: "Audit",
		group: "settings",
		keywords: ["audit", "log", "history", "changes"],
		icon: FileSearch,
		href: "/settings/audit",
		permission: "api:settings:admin",
	},
	{
		id: "settings-support",
		label: "Support",
		group: "settings",
		keywords: ["support", "help", "contact"],
		icon: LifeBuoy,
		href: "/settings/support",
	},

	// ─── Quick Settings ──────────────────────────────────────────────────
	{
		id: "qs-dark-mode",
		label: "Toggle Dark Mode",
		group: "quick-settings",
		description: "Switch between light and dark themes",
		keywords: ["dark mode", "light mode", "theme", "toggle"],
		icon: Sun,
	},
	{
		id: "qs-glucose-units",
		label: "Switch Glucose Units",
		group: "quick-settings",
		description: "Toggle between mg/dL and mmol/L",
		keywords: ["glucose units", "mg/dl", "mmol/l", "units"],
		icon: Ruler,
	},
	{
		id: "qs-chart-lookback",
		label: "Change Chart Lookback",
		group: "quick-settings",
		description: "Adjust the time window for charts",
		keywords: ["lookback", "time range", "chart period", "hours"],
		icon: ZoomIn,
	},

	// ─── Actions ─────────────────────────────────────────────────────────
	{
		id: "action-add-treatment",
		label: "Add Treatment",
		group: "actions",
		description: "Log a new treatment entry",
		keywords: ["add treatment", "log", "bolus", "carbs"],
		icon: Plus,
	},
	{
		id: "action-add-food",
		label: "Add Food Entry",
		group: "actions",
		description: "Add a food item to the database",
		keywords: ["add food", "nutrition", "new food"],
		icon: CirclePlus,
	},
	{
		id: "action-manual-sync",
		label: "Manual Sync",
		group: "actions",
		description: "Trigger a manual data sync",
		keywords: ["sync", "refresh", "fetch", "update"],
		icon: RefreshCw,
	},
];
