{{- if and (not .Values.instanceKey.existingSecret) .Values.instanceKey.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nocturne.fullname" . }}-instance-key
  labels: {{- include "nocturne.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "nocturne.instanceKeySecretKey" . }}: {{ .Values.instanceKey.value | quote }}
{{- else if and (not .Values.instanceKey.existingSecret) (not .Values.instanceKey.value) -}}
{{- fail "instanceKey.existingSecret OR instanceKey.value must be set" -}}
{{- end -}}
