apiVersion: v1
kind: Service
metadata:
  name: {{ include "nocturne.web.fullname" . }}
  labels:
    {{- include "nocturne.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
  selector: {{- include "nocturne.web.selectorLabels" . | nindent 4 }}
