// AUTO-GENERATED - DO NOT EDIT
// Generated by openapi-remote-codegen
// Source: openapi.json
//
import {
  AccessRequestClient,
  ActivityClient,
  ActogramClient,
  AlertCustomSoundsClient,
  AlertInvitesClient,
  AlertReplayClient,
  AlertRulesClient,
  AlertsClient,
  AnalyticsClient,
  ApsSnapshotClient,
  AuditClient,
  AvatarClient,
  BatteryClient,
  BGCheckClient,
  BodyWeightClient,
  BolusClient,
  BolusCalculationClient,
  CalibrationClient,
  ChartDataClient,
  ChatIdentityClient,
  ChatIdentityDirectoryClient,
  ClockFacesClient,
  CoachMarkClient,
  CompatibilityClient,
  CompressionLowClient,
  ConfigurationClient,
  ConnectedAppsClient,
  ConnectorFoodEntriesClient,
  ConnectorStatusClient,
  CorrelationClient,
  CurrentTherapyStateClient,
  DataOverviewClient,
  DebugClient,
  DeduplicationClient,
  DevAdminClient,
  DeviceAgeClient,
  DeviceCatalogClient,
  DeviceEventClient,
  DirectGrantClient,
  DiscrepancyClient,
  FoodsClient,
  GlucoseProcessingSettingsClient,
  GuestLinkClient,
  HeartRateClient,
  InsulinCatalogClient,
  LinkedPlatformsClient,
  MealMatchingClient,
  MemberInviteClient,
  MetadataClient,
  MeterGlucoseClient,
  MigrationClient,
  MyFitnessPalSettingsClient,
  MyPermissionsClient,
  MyTenantsClient,
  NightscoutTransitionClient,
  NoteClient,
  NotificationsClient,
  NutritionClient,
  OAuthClient,
  OidcClient,
  WellKnownClient,
  OidcProviderAdminClient,
  PasskeyClient,
  PatientRecordClient,
  PlatformClient,
  PlatformSettingsClient,
  PredictionClient,
  ProcessingClient,
  ProfileClient,
  PumpSnapshotClient,
  RetrospectiveClient,
  RoleClient,
  SensorGlucoseClient,
  ServicesClient,
  SetupClient,
  StateSpansClient,
  StatisticsClient,
  StatusClient,
  StepCountClient,
  SubjectAdminClient,
  SummaryClient,
  SupportClient,
  SystemClient,
  SystemEventsClient,
  TenantClient,
  TenantAlertSettingsClient,
  TotpClient,
  TrackerAlertsClient,
  TrackersClient,
  UISettingsClient,
  UploaderSnapshotClient,
  UserPreferencesClient,
  WebhookSettingsClient
} from "./generated/nocturne-api-client";

/**
 * API client wrapper.
 * Provides typed access to all backend endpoints.
 */
export class ApiClient {
  public readonly baseUrl: string;
  public readonly accessRequest: AccessRequestClient;
  public readonly activity: ActivityClient;
  public readonly actogram: ActogramClient;
  public readonly alertCustomSounds: AlertCustomSoundsClient;
  public readonly alertInvites: AlertInvitesClient;
  public readonly alertReplay: AlertReplayClient;
  public readonly alertRules: AlertRulesClient;
  public readonly alerts: AlertsClient;
  public readonly analytics: AnalyticsClient;
  public readonly apsSnapshot: ApsSnapshotClient;
  public readonly audit: AuditClient;
  public readonly avatar: AvatarClient;
  public readonly battery: BatteryClient;
  public readonly bGCheck: BGCheckClient;
  public readonly bodyWeight: BodyWeightClient;
  public readonly bolus: BolusClient;
  public readonly bolusCalculation: BolusCalculationClient;
  public readonly calibration: CalibrationClient;
  public readonly chartData: ChartDataClient;
  public readonly chatIdentity: ChatIdentityClient;
  public readonly chatIdentityDirectory: ChatIdentityDirectoryClient;
  public readonly clockFaces: ClockFacesClient;
  public readonly coachMark: CoachMarkClient;
  public readonly compatibility: CompatibilityClient;
  public readonly compressionLow: CompressionLowClient;
  public readonly configuration: ConfigurationClient;
  public readonly connectedApps: ConnectedAppsClient;
  public readonly connectorFoodEntries: ConnectorFoodEntriesClient;
  public readonly connectorStatus: ConnectorStatusClient;
  public readonly correlation: CorrelationClient;
  public readonly currentTherapyState: CurrentTherapyStateClient;
  public readonly dataOverview: DataOverviewClient;
  public readonly debug: DebugClient;
  public readonly deduplication: DeduplicationClient;
  public readonly devAdmin: DevAdminClient;
  public readonly deviceAge: DeviceAgeClient;
  public readonly deviceCatalog: DeviceCatalogClient;
  public readonly deviceEvent: DeviceEventClient;
  public readonly directGrant: DirectGrantClient;
  public readonly discrepancy: DiscrepancyClient;
  public readonly foodsV4: FoodsClient;
  public readonly glucoseProcessingSettings: GlucoseProcessingSettingsClient;
  public readonly guestLink: GuestLinkClient;
  public readonly heartRate: HeartRateClient;
  public readonly insulinCatalog: InsulinCatalogClient;
  public readonly linkedPlatforms: LinkedPlatformsClient;
  public readonly mealMatching: MealMatchingClient;
  public readonly memberInvite: MemberInviteClient;
  public readonly metadata: MetadataClient;
  public readonly meterGlucose: MeterGlucoseClient;
  public readonly migration: MigrationClient;
  public readonly myFitnessPalSettings: MyFitnessPalSettingsClient;
  public readonly myPermissions: MyPermissionsClient;
  public readonly myTenants: MyTenantsClient;
  public readonly nightscoutTransition: NightscoutTransitionClient;
  public readonly note: NoteClient;
  public readonly notifications: NotificationsClient;
  public readonly nutrition: NutritionClient;
  public readonly oAuth: OAuthClient;
  public readonly oidc: OidcClient;
  public readonly oidcDiscovery: WellKnownClient;
  public readonly oidcProviderAdmin: OidcProviderAdminClient;
  public readonly passkey: PasskeyClient;
  public readonly patientRecord: PatientRecordClient;
  public readonly platform: PlatformClient;
  public readonly platformSettings: PlatformSettingsClient;
  public readonly predictions: PredictionClient;
  public readonly processing: ProcessingClient;
  public readonly profile: ProfileClient;
  public readonly pumpSnapshot: PumpSnapshotClient;
  public readonly retrospective: RetrospectiveClient;
  public readonly role: RoleClient;
  public readonly sensorGlucose: SensorGlucoseClient;
  public readonly services: ServicesClient;
  public readonly setup: SetupClient;
  public readonly stateSpans: StateSpansClient;
  public readonly statistics: StatisticsClient;
  public readonly status: StatusClient;
  public readonly stepCount: StepCountClient;
  public readonly subjectAdmin: SubjectAdminClient;
  public readonly summary: SummaryClient;
  public readonly support: SupportClient;
  public readonly system: SystemClient;
  public readonly systemEvents: SystemEventsClient;
  public readonly tenant: TenantClient;
  public readonly tenantAlertSettings: TenantAlertSettingsClient;
  public readonly totp: TotpClient;
  public readonly trackerAlerts: TrackerAlertsClient;
  public readonly trackers: TrackersClient;
  public readonly uiSettings: UISettingsClient;
  public readonly uploaderSnapshot: UploaderSnapshotClient;
  public readonly userPreferences: UserPreferencesClient;
  public readonly webhookSettings: WebhookSettingsClient;

  constructor(
    baseUrl: string,
    http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }
  ) {
    const apiBaseUrl = baseUrl;
    this.baseUrl = apiBaseUrl;

    this.accessRequest = new AccessRequestClient(apiBaseUrl, http);
    this.activity = new ActivityClient(apiBaseUrl, http);
    this.actogram = new ActogramClient(apiBaseUrl, http);
    this.alertCustomSounds = new AlertCustomSoundsClient(apiBaseUrl, http);
    this.alertInvites = new AlertInvitesClient(apiBaseUrl, http);
    this.alertReplay = new AlertReplayClient(apiBaseUrl, http);
    this.alertRules = new AlertRulesClient(apiBaseUrl, http);
    this.alerts = new AlertsClient(apiBaseUrl, http);
    this.analytics = new AnalyticsClient(apiBaseUrl, http);
    this.apsSnapshot = new ApsSnapshotClient(apiBaseUrl, http);
    this.audit = new AuditClient(apiBaseUrl, http);
    this.avatar = new AvatarClient(apiBaseUrl, http);
    this.battery = new BatteryClient(apiBaseUrl, http);
    this.bGCheck = new BGCheckClient(apiBaseUrl, http);
    this.bodyWeight = new BodyWeightClient(apiBaseUrl, http);
    this.bolus = new BolusClient(apiBaseUrl, http);
    this.bolusCalculation = new BolusCalculationClient(apiBaseUrl, http);
    this.calibration = new CalibrationClient(apiBaseUrl, http);
    this.chartData = new ChartDataClient(apiBaseUrl, http);
    this.chatIdentity = new ChatIdentityClient(apiBaseUrl, http);
    this.chatIdentityDirectory = new ChatIdentityDirectoryClient(apiBaseUrl, http);
    this.clockFaces = new ClockFacesClient(apiBaseUrl, http);
    this.coachMark = new CoachMarkClient(apiBaseUrl, http);
    this.compatibility = new CompatibilityClient(apiBaseUrl, http);
    this.compressionLow = new CompressionLowClient(apiBaseUrl, http);
    this.configuration = new ConfigurationClient(apiBaseUrl, http);
    this.connectedApps = new ConnectedAppsClient(apiBaseUrl, http);
    this.connectorFoodEntries = new ConnectorFoodEntriesClient(apiBaseUrl, http);
    this.connectorStatus = new ConnectorStatusClient(apiBaseUrl, http);
    this.correlation = new CorrelationClient(apiBaseUrl, http);
    this.currentTherapyState = new CurrentTherapyStateClient(apiBaseUrl, http);
    this.dataOverview = new DataOverviewClient(apiBaseUrl, http);
    this.debug = new DebugClient(apiBaseUrl, http);
    this.deduplication = new DeduplicationClient(apiBaseUrl, http);
    this.devAdmin = new DevAdminClient(apiBaseUrl, http);
    this.deviceAge = new DeviceAgeClient(apiBaseUrl, http);
    this.deviceCatalog = new DeviceCatalogClient(apiBaseUrl, http);
    this.deviceEvent = new DeviceEventClient(apiBaseUrl, http);
    this.directGrant = new DirectGrantClient(apiBaseUrl, http);
    this.discrepancy = new DiscrepancyClient(apiBaseUrl, http);
    this.foodsV4 = new FoodsClient(apiBaseUrl, http);
    this.glucoseProcessingSettings = new GlucoseProcessingSettingsClient(apiBaseUrl, http);
    this.guestLink = new GuestLinkClient(apiBaseUrl, http);
    this.heartRate = new HeartRateClient(apiBaseUrl, http);
    this.insulinCatalog = new InsulinCatalogClient(apiBaseUrl, http);
    this.linkedPlatforms = new LinkedPlatformsClient(apiBaseUrl, http);
    this.mealMatching = new MealMatchingClient(apiBaseUrl, http);
    this.memberInvite = new MemberInviteClient(apiBaseUrl, http);
    this.metadata = new MetadataClient(apiBaseUrl, http);
    this.meterGlucose = new MeterGlucoseClient(apiBaseUrl, http);
    this.migration = new MigrationClient(apiBaseUrl, http);
    this.myFitnessPalSettings = new MyFitnessPalSettingsClient(apiBaseUrl, http);
    this.myPermissions = new MyPermissionsClient(apiBaseUrl, http);
    this.myTenants = new MyTenantsClient(apiBaseUrl, http);
    this.nightscoutTransition = new NightscoutTransitionClient(apiBaseUrl, http);
    this.note = new NoteClient(apiBaseUrl, http);
    this.notifications = new NotificationsClient(apiBaseUrl, http);
    this.nutrition = new NutritionClient(apiBaseUrl, http);
    this.oAuth = new OAuthClient(apiBaseUrl, http);
    this.oidc = new OidcClient(apiBaseUrl, http);
    this.oidcDiscovery = new WellKnownClient(apiBaseUrl, http);
    this.oidcProviderAdmin = new OidcProviderAdminClient(apiBaseUrl, http);
    this.passkey = new PasskeyClient(apiBaseUrl, http);
    this.patientRecord = new PatientRecordClient(apiBaseUrl, http);
    this.platform = new PlatformClient(apiBaseUrl, http);
    this.platformSettings = new PlatformSettingsClient(apiBaseUrl, http);
    this.predictions = new PredictionClient(apiBaseUrl, http);
    this.processing = new ProcessingClient(apiBaseUrl, http);
    this.profile = new ProfileClient(apiBaseUrl, http);
    this.pumpSnapshot = new PumpSnapshotClient(apiBaseUrl, http);
    this.retrospective = new RetrospectiveClient(apiBaseUrl, http);
    this.role = new RoleClient(apiBaseUrl, http);
    this.sensorGlucose = new SensorGlucoseClient(apiBaseUrl, http);
    this.services = new ServicesClient(apiBaseUrl, http);
    this.setup = new SetupClient(apiBaseUrl, http);
    this.stateSpans = new StateSpansClient(apiBaseUrl, http);
    this.statistics = new StatisticsClient(apiBaseUrl, http);
    this.status = new StatusClient(apiBaseUrl, http);
    this.stepCount = new StepCountClient(apiBaseUrl, http);
    this.subjectAdmin = new SubjectAdminClient(apiBaseUrl, http);
    this.summary = new SummaryClient(apiBaseUrl, http);
    this.support = new SupportClient(apiBaseUrl, http);
    this.system = new SystemClient(apiBaseUrl, http);
    this.systemEvents = new SystemEventsClient(apiBaseUrl, http);
    this.tenant = new TenantClient(apiBaseUrl, http);
    this.tenantAlertSettings = new TenantAlertSettingsClient(apiBaseUrl, http);
    this.totp = new TotpClient(apiBaseUrl, http);
    this.trackerAlerts = new TrackerAlertsClient(apiBaseUrl, http);
    this.trackers = new TrackersClient(apiBaseUrl, http);
    this.uiSettings = new UISettingsClient(apiBaseUrl, http);
    this.uploaderSnapshot = new UploaderSnapshotClient(apiBaseUrl, http);
    this.userPreferences = new UserPreferencesClient(apiBaseUrl, http);
    this.webhookSettings = new WebhookSettingsClient(apiBaseUrl, http);
  }
}

// Export the generated client types for use in components
export * from "./generated/nocturne-api-client";
