import {
	AlertRuleSeverity,
	ChannelType,
	AlertConditionType,
	TempBasalMetric,
	GlucoseBucket,
	PumpModeState,
	StateSpanCategory,
	DayOfWeek,
} from "$api-clients";
import type {
	AlertRuleResponse,
	ThresholdCondition,
	RateOfChangeCondition,
	SignalLossCondition,
	StalenessCondition,
	PredictedCondition,
	TrendCondition,
	TimeOfDayCondition,
	IobCondition,
	CobCondition,
	ReservoirCondition,
	SiteAgeCondition,
	SensorAgeCondition,
	AlertStateCondition,
	LoopStaleCondition,
	LoopEnactionStaleCondition,
	PumpSuspendedCondition,
	PumpBatteryCondition,
	TempBasalCondition,
	UploaderBatteryCondition,
	OverrideActiveCondition,
	SensitivityRatioCondition,
	DoNotDisturbCondition,
	GlucoseBucketCondition,
	TimeSinceLastCarbCondition,
	TimeSinceLastBolusCondition,
	DayOfWeekCondition,
	PumpStateCondition,
	StateSpanActiveCondition,
} from "$api-clients";

// All condition payload records are generated by NSwag from the C# records in
// `Nocturne.Core.Models.AlertModels` (see the [JsonPropertyName] attributes there
// pinning the wire names to snake_case). Editor-only adornments live here only
// where they don't exist on the wire — currently just `_uid`.

export { TempBasalMetric, GlucoseBucket, PumpModeState, StateSpanCategory, DayOfWeek };
export type {
	ThresholdCondition,
	RateOfChangeCondition,
	SignalLossCondition,
	StalenessCondition,
	PredictedCondition,
	TrendCondition,
	TimeOfDayCondition,
	IobCondition,
	CobCondition,
	ReservoirCondition,
	SiteAgeCondition,
	SensorAgeCondition,
	AlertStateCondition,
	LoopStaleCondition,
	LoopEnactionStaleCondition,
	PumpSuspendedCondition,
	PumpBatteryCondition,
	TempBasalCondition,
	UploaderBatteryCondition,
	OverrideActiveCondition,
	SensitivityRatioCondition,
	DoNotDisturbCondition,
	GlucoseBucketCondition,
	TimeSinceLastCarbCondition,
	TimeSinceLastBolusCondition,
	DayOfWeekCondition,
	PumpStateCondition,
	StateSpanActiveCondition,
};

/**
 * The set of valid {@link ConditionNode.type} values. Mirrors the backend
 * <c>AlertConditionType</c> enum — kebab-/snake-case strings.
 */
export type ConditionKind = `${AlertConditionType}`;

export type ComparisonOperator = ">=" | ">" | "<=" | "<";

/**
 * Staleness is conceptually directional ("more than N minutes since…"), so the
 * loop-staleness kinds only accept `>` and `>=`. The wider {@link StalenessCondition}
 * (BG staleness) was shipped accepting all four operators and predates this
 * narrowing; widening would break stored rules using `<` for auto-resolve.
 */
export type StalenessOperator = ">" | ">=";

export type TrendBucket =
	| "falling_fast"
	| "falling"
	| "flat"
	| "rising"
	| "rising_fast";

/**
 * Composite condition (AND/OR group). The wire-side child list points back at
 * the editor's {@link ConditionNode}, not the bare generated record, so the
 * `_uid` extension propagates through nested groups.
 */
export interface CompositePayload {
	operator: "and" | "or";
	conditions: ConditionNode[];
}

export interface NotPayload {
	child: ConditionNode;
}

export interface SustainedPayload {
	minutes: number;
	child: ConditionNode;
}

/**
 * The editor's recursive condition tree. Field shapes for leaf nodes come
 * straight from the generated client; the only editor-only addition is `_uid`,
 * stripped before the tree is sent back over the wire (see
 * {@link stripEditorFields}).
 *
 * `composite`/`not`/`sustained` use editor-aware payloads here so the `_uid`
 * extension propagates through nested groups — the generated wire types refer
 * to a bare `ConditionNode` without it.
 */
export interface ConditionNode {
	type: ConditionKind;
	/**
	 * Editor-only stable identity for keyed `{#each}` blocks. Set on
	 * construction (`defaultPayload`/`nodeFromApi`); stripped before the node
	 * is sent over the wire by {@link stripEditorFields}. Index-based keys
	 * cause Svelte 5 to re-bind the wrong nested editor instance after a
	 * sibling is removed; this avoids that.
	 */
	_uid?: string;
	composite?: CompositePayload;
	not?: NotPayload;
	sustained?: SustainedPayload;
	threshold?: ThresholdCondition;
	rate_of_change?: RateOfChangeCondition;
	signal_loss?: SignalLossCondition;
	staleness?: StalenessCondition;
	predicted?: PredictedCondition;
	trend?: TrendCondition;
	time_of_day?: TimeOfDayCondition;
	iob?: IobCondition;
	cob?: CobCondition;
	reservoir?: ReservoirCondition;
	site_age?: SiteAgeCondition;
	sensor_age?: SensorAgeCondition;
	alert_state?: AlertStateCondition;
	loop_stale?: LoopStaleCondition;
	loop_enaction_stale?: LoopEnactionStaleCondition;
	pump_suspended?: PumpSuspendedCondition;
	pump_battery?: PumpBatteryCondition;
	temp_basal?: TempBasalCondition;
	uploader_battery?: UploaderBatteryCondition;
	override_active?: OverrideActiveCondition;
	sensitivity_ratio?: SensitivityRatioCondition;
	do_not_disturb?: DoNotDisturbCondition;
	glucose_bucket?: GlucoseBucketCondition;
	time_since_last_carb?: TimeSinceLastCarbCondition;
	time_since_last_bolus?: TimeSinceLastBolusCondition;
	day_of_week?: DayOfWeekCondition;
	pump_state?: PumpStateCondition;
	state_span_active?: StateSpanActiveCondition;
}

function newUid(): string {
	if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
		return crypto.randomUUID();
	}
	return Math.random().toString(36).slice(2);
}

/**
 * Wrap a non-composite node in a single-child AND group, leaving composite
 * nodes untouched. The inline rule builder always edits at the group level —
 * single-leaf rules are still rendered as one IF row inside an implicit AND.
 * The save path (caller-side) flattens single-child composites back to the
 * inner node so the wire shape doesn't grow a redundant wrapper.
 */
export function ensureCompositeRoot(node: ConditionNode): ConditionNode {
	if (node.type === "composite") return node;
	return {
		type: "composite",
		_uid: newUid(),
		composite: { operator: "and", conditions: [node] },
	};
}

/**
 * Inverse of {@link ensureCompositeRoot}. Returns the inner node when the root
 * is a composite holding exactly one child; otherwise returns the input
 * unchanged. Use this when serialising the editor's tree back to the API so
 * single-leaf rules stay flat on the wire.
 */
export function flattenSingleChildRoot(node: ConditionNode): ConditionNode {
	if (
		node.type === "composite" &&
		node.composite &&
		node.composite.conditions.length === 1
	) {
		return node.composite.conditions[0];
	}
	return node;
}

// ---------------------------------------------------------------------------
// Default payloads per kind
// ---------------------------------------------------------------------------

export function defaultPayload(kind: ConditionKind): ConditionNode {
	const node = makeDefault(kind);
	node._uid = newUid();
	return node;
}

function makeDefault(kind: ConditionKind): ConditionNode {
	switch (kind) {
		case "composite":
			return {
				type: "composite",
				composite: {
					operator: "and",
					conditions: [defaultPayload("threshold")],
				},
			};
		case "not":
			return { type: "not", not: { child: defaultPayload("threshold") } };
		case "sustained":
			return {
				type: "sustained",
				sustained: { minutes: 15, child: defaultPayload("threshold") },
			};
		case "threshold":
			return {
				type: "threshold",
				threshold: { direction: "below", value: 70 },
			};
		case "rate_of_change":
			return {
				type: "rate_of_change",
				rate_of_change: { direction: "falling", rate: 3 },
			};
		case "staleness":
			return {
				type: "staleness",
				staleness: { operator: ">=", value: 15 },
			};
		case "predicted":
			return {
				type: "predicted",
				predicted: { operator: "<=", value: 70, within_minutes: 30 },
			};
		case "trend":
			return { type: "trend", trend: { bucket: "falling" } };
		case "time_of_day":
			return {
				type: "time_of_day",
				time_of_day: { from: "22:00", to: "06:00" },
			};
		case "iob":
			return { type: "iob", iob: { operator: ">=", value: 1 } };
		case "cob":
			return { type: "cob", cob: { operator: ">=", value: 10 } };
		case "reservoir":
			return {
				type: "reservoir",
				reservoir: { operator: "<=", value: 10 },
			};
		case "site_age":
			return {
				type: "site_age",
				site_age: { operator: ">=", value: 72 },
			};
		case "sensor_age":
			return {
				type: "sensor_age",
				sensor_age: { operator: ">=", value: 10 },
			};
		case "alert_state":
			return {
				type: "alert_state",
				alert_state: { alert_id: "", state: "firing" },
			};
		case "loop_stale":
			return {
				type: "loop_stale",
				loop_stale: { operator: ">", minutes: 15 },
			};
		case "loop_enaction_stale":
			return {
				type: "loop_enaction_stale",
				loop_enaction_stale: { operator: ">", minutes: 15 },
			};
		case "pump_suspended":
			return {
				type: "pump_suspended",
				pump_suspended: { is_active: true },
			};
		case "pump_battery":
			return {
				type: "pump_battery",
				pump_battery: { operator: "<=", value: 20 },
			};
		case "temp_basal":
			return {
				type: "temp_basal",
				temp_basal: { metric: "rate", operator: ">=", value: 1 },
			};
		case "uploader_battery":
			return {
				type: "uploader_battery",
				uploader_battery: { operator: "<=", value: 20 },
			};
		case "override_active":
			return {
				type: "override_active",
				override_active: { is_active: true },
			};
		case "sensitivity_ratio":
			return {
				type: "sensitivity_ratio",
				sensitivity_ratio: { operator: "<", value: 0.8 },
			};
		case "do_not_disturb":
			return {
				type: "do_not_disturb",
				do_not_disturb: { is_active: true },
			};
		case "signal_loss":
			return {
				type: "signal_loss",
				signal_loss: { timeout_minutes: 30 },
			};
		case "glucose_bucket":
			return {
				type: "glucose_bucket",
				glucose_bucket: { buckets: [GlucoseBucket.Low] },
			};
		case "time_since_last_carb":
			// NSwag types AlertComparisonOperator as a numeric enum, but the wire
			// format is the symbol literal (">", ">=", …) thanks to
			// [JsonStringEnumMemberName] on the C# side. We carry the string in
			// the editor and cast at the type boundary.
			return {
				type: "time_since_last_carb",
				time_since_last_carb: {
					operator: ">=" as unknown as TimeSinceLastCarbCondition["operator"],
					minutes: 30,
				},
			};
		case "time_since_last_bolus":
			return {
				type: "time_since_last_bolus",
				time_since_last_bolus: {
					operator: ">=" as unknown as TimeSinceLastBolusCondition["operator"],
					minutes: 60,
				},
			};
		case "day_of_week":
			return {
				type: "day_of_week",
				day_of_week: { days: [DayOfWeek.Monday] },
			};
		case "pump_state":
			return {
				type: "pump_state",
				pump_state: { mode: PumpModeState.Suspended, is_active: true },
			};
		case "state_span_active":
			return {
				type: "state_span_active",
				state_span_active: {
					category: StateSpanCategory.Override,
					is_active: true,
				},
			};
	}
}

// ---------------------------------------------------------------------------
// (De)serialise to/from API conditionParams field
// ---------------------------------------------------------------------------

/**
 * Wrap a full <see cref="ConditionNode"/> envelope (i.e. `{type, ...payload}`)
 * coming back from the API into the editor's tree. Used by save/load paths
 * where the wire shape is a self-describing envelope rather than a side-by-
 * side `(conditionType, conditionParams)` pair — notably auto-resolve, which
 * stores a single `autoResolveParams` blob the backend deserialises directly
 * into a polymorphic <see cref="ConditionNode"/>.
 */
export function nodeFromApiEnvelope(envelope: unknown): ConditionNode | null {
	if (!envelope || typeof envelope !== "object") return null;
	const env = envelope as { type?: unknown };
	if (typeof env.type !== "string") return null;
	const kind = env.type as ConditionKind;
	const payload = (envelope as Record<string, unknown>)[kind];
	return nodeFromApi(kind, payload);
}

/**
 * Wrap a kind + opaque API payload into a `ConditionNode`. The API stores only
 * the kind-specific payload (e.g. `{direction, value}`); the FE keeps the kind
 * alongside it so a single recursive editor can dispatch on `node.type`.
 */
export function nodeFromApi(
	kind: string | undefined,
	params: unknown,
): ConditionNode | null {
	if (!kind) return null;
	if (params === null || params === undefined) return null;
	const k = kind as ConditionKind;
	const node: ConditionNode = { type: k, _uid: newUid() };
	(node as Record<string, unknown>)[k] = params;
	// Defensive: a malformed loop-staleness rule with a `<`/`<=` operator would
	// render an unselectable value in the editor (the dropdown only offers `>`
	// and `>=`). Coerce on inbound and warn so we notice if it ever happens.
	coerceStalenessOperator(node);
	// Recursively assign uids to nested nodes so keyed each-blocks have stable
	// identity for every level of the tree, not just the root.
	assignUidsRecursive(node);
	return node;
}

function coerceStalenessOperator(node: ConditionNode): void {
	const payload =
		node.type === "loop_stale"
			? node.loop_stale
			: node.type === "loop_enaction_stale"
				? node.loop_enaction_stale
				: null;
	if (!payload) return;
	const op = payload.operator as ComparisonOperator;
	if (op === "<" || op === "<=") {
		// eslint-disable-next-line no-console
		console.warn(
			`[alerts] coercing ${node.type} operator '${op}' → '>' (staleness only supports '>' / '>=')`,
		);
		payload.operator = ">";
	}
}

function assignUidsRecursive(node: ConditionNode): void {
	if (!node._uid) node._uid = newUid();
	if (node.composite?.conditions) {
		for (const child of node.composite.conditions) assignUidsRecursive(child);
	}
	if (node.not?.child) assignUidsRecursive(node.not.child);
	if (node.sustained?.child) assignUidsRecursive(node.sustained.child);
}

/**
 * Returns a deep copy of `node` with every editor-only `_uid` field stripped.
 * Use this when sending the full ConditionNode envelope to the backend (e.g.
 * `autoResolveParams`) so the editor's internal identity doesn't leak into
 * stored configuration.
 */
export function stripEditorFields(node: ConditionNode): ConditionNode {
	const cleaned: ConditionNode = { type: node.type };
	for (const k of Object.keys(node) as (keyof ConditionNode)[]) {
		if (k === "_uid" || k === "type") continue;
		const value = node[k];
		if (value === undefined) continue;
		// Recurse into nested children so uids in the subtree are also stripped.
		if (k === "composite" && node.composite) {
			cleaned.composite = {
				operator: node.composite.operator,
				conditions: node.composite.conditions.map(stripEditorFields),
			};
		} else if (k === "not" && node.not) {
			cleaned.not = { child: stripEditorFields(node.not.child) };
		} else if (k === "sustained" && node.sustained) {
			cleaned.sustained = {
				minutes: node.sustained.minutes,
				child: stripEditorFields(node.sustained.child),
			};
		} else {
			(cleaned as Record<string, unknown>)[k] = value;
		}
	}
	return cleaned;
}

/**
 * Extract the kind-specific payload for the API. Returns `null` when there's
 * no node.
 */
export function nodeToApi(
	node: ConditionNode | null,
): { conditionType: string; conditionParams: unknown } | null {
	if (!node) return null;
	const params = (node as Record<string, unknown>)[node.type];
	return { conditionType: node.type, conditionParams: params ?? {} };
}

/**
 * Serialise the editor's {@link RuleEditorState} into the wire-format body
 * shared by {@link CreateAlertRuleRequest} and {@link UpdateAlertRuleRequest}.
 *
 * Strips `_uid` markers and flattens single-child composite roots so the output
 * is identical for any two semantically-equal editor states regardless of their
 * internal identity markers. Use this both for the actual save call and for
 * dirty detection (compare `JSON.stringify` of current vs. saved body).
 */
export function buildBody(state: RuleEditorState) {
	const flat = flattenSingleChildRoot(state.condition!);
	const api = nodeToApi(flat);
	return {
		name: state.name,
		description: state.description || undefined,
		conditionType: api?.conditionType as AlertConditionType,
		conditionParams: api?.conditionParams,
		isEnabled: state.isEnabled,
		sortOrder: state.sortOrder,
		severity: state.severity,
		allowThroughDnd: state.allowThroughDnd,
		autoResolveEnabled: state.autoResolveEnabled,
		autoResolveParams: state.autoResolveCondition
			? stripEditorFields(flattenSingleChildRoot(state.autoResolveCondition))
			: undefined,
		clientConfiguration: {
			...state.clientConfig,
			snooze: {
				...state.clientConfig.snooze,
				conditions: state.clientConfig.snooze.conditions.map((c) =>
					stripEditorFields(flattenSingleChildRoot(c))
				),
			},
		},
		channels: state.channels.map((c) => ({
			channelType: c.channelType,
			destination: c.destination || undefined,
			destinationLabel: c.destinationLabel || undefined,
		})),
	};
}

// ---------------------------------------------------------------------------
// Existing client-config / schedule shapes (unchanged)
// ---------------------------------------------------------------------------

export interface AudioConfig {
	enabled: boolean;
	sound: string;
	customSoundId: string | null;
	ascending: boolean;
	startVolume: number;
	maxVolume: number;
	ascendDurationSeconds: number;
	repeatCount: number;
}

export interface VisualConfig {
	flashEnabled: boolean;
	flashColor: string;
	persistentBanner: boolean;
	wakeScreen: boolean;
}

export interface SnoozeConfig {
	defaultMinutes: number;
	options: number[];
	maxCount: number;
	smartSnooze: boolean;
	smartSnoozeExtendMinutes: number;
	/**
	 * Optional conditions that must all hold for the snooze to extend. When
	 * empty, the backend falls back to the trend-favorable heuristic.
	 */
	conditions: ConditionNode[];
}

export interface ClientConfiguration {
	audio: AudioConfig;
	visual: VisualConfig;
	snooze: SnoozeConfig;
}

/**
 * Editor-shape for a single delivery channel. Mirrors the API's
 * <c>AlertRuleChannelResponse</c> minus the server-managed <c>id</c> and
 * <c>sortOrder</c> — the editor maintains list order positionally.
 *
 * <c>_uid</c> is an editor-only stable identity used as the key in
 * <c>{#each channels (ch._uid)}</c> blocks; without it, keying by index
 * causes Svelte 5 to re-bind input elements to the wrong row when channels
 * are removed mid-list. Stripped before sending over the wire.
 */
export interface ChannelDef {
	_uid?: string;
	channelType: ChannelType;
	destination: string;
	destinationLabel?: string | null;
}

export interface RuleEditorState {
	name: string;
	description: string;
	severity: AlertRuleSeverity;
	condition: ConditionNode | null;
	autoResolveEnabled: boolean;
	autoResolveCondition: ConditionNode | null;
	sortOrder: number;
	isEnabled: boolean;
	clientConfig: ClientConfiguration;
	/** Flat list of delivery channels. */
	channels: ChannelDef[];
	/** When true, this rule still fires while the tenant is in Do Not Disturb
	 *  mode. Critical-severity rules implicitly bypass DND regardless. */
	allowThroughDnd: boolean;
}

export function defaultClientConfig(): ClientConfiguration {
	return {
		audio: {
			enabled: true,
			sound: "alarm-default",
			customSoundId: null,
			ascending: false,
			startVolume: 50,
			maxVolume: 80,
			ascendDurationSeconds: 30,
			repeatCount: 2,
		},
		visual: {
			flashEnabled: false,
			flashColor: "#ff0000",
			persistentBanner: true,
			wakeScreen: false,
		},
		snooze: {
			defaultMinutes: 15,
			options: [5, 15, 30, 60],
			maxCount: 5,
			smartSnooze: false,
			smartSnoozeExtendMinutes: 10,
			conditions: [],
		},
	};
}

export function defaultChannels(): ChannelDef[] {
	return [
		{
			_uid: newUid(),
			channelType: ChannelType.WebPush,
			destination: "",
			destinationLabel: "",
		},
	];
}

function defaultState(): RuleEditorState {
	return {
		name: "",
		description: "",
		severity: AlertRuleSeverity.Warning,
		condition: ensureCompositeRoot(defaultPayload("threshold")),
		autoResolveEnabled: false,
		autoResolveCondition: null,
		sortOrder: 0,
		isEnabled: true,
		clientConfig: defaultClientConfig(),
		channels: defaultChannels(),
		allowThroughDnd: false,
	};
}

/**
 * Snooze conditions are a frontend-only client-config extension. NSwag's
 * generated type for `clientConfiguration.snooze` doesn't model them, so we
 * read them off the raw object defensively.
 */
function parseSnoozeConditions(snooze: unknown): ConditionNode[] {
	if (!snooze || typeof snooze !== "object") return [];
	const raw = (snooze as Record<string, unknown>).conditions;
	if (!Array.isArray(raw)) return [];
	const out: ConditionNode[] = [];
	for (const entry of raw) {
		if (entry && typeof entry === "object" && typeof (entry as { type?: unknown }).type === "string") {
			// Normalise to a composite root: the inline rule builder always edits
			// at the group level, and pre-existing snooze entries (which were
			// stored as flat leaves under the legacy SnoozeTab) need wrapping
			// before they can be mounted.
			out.push(ensureCompositeRoot(entry as ConditionNode));
		}
	}
	return out;
}

export function parseRule(r: AlertRuleResponse | null): RuleEditorState {
	if (!r) return defaultState();

	const rawCondition =
		nodeFromApi(r.conditionType, r.conditionParams) ?? defaultPayload("threshold");
	// The inline rule builder always edits at the group level, so wrap leaf
	// roots in a single-child AND group on the way in. The corresponding
	// flattenSingleChildRoot is applied on save by the caller.
	const condition = ensureCompositeRoot(rawCondition);
	// Auto-resolve is stored as a full ConditionNode envelope (the backend
	// deserialises r.autoResolveParams directly into a polymorphic node) — read
	// it through the envelope helper, then normalise to a composite root so
	// the inline rule builder can edit it in place.
	const rawAutoResolve = nodeFromApiEnvelope(r.autoResolveParams);
	const autoResolveCondition = rawAutoResolve ? ensureCompositeRoot(rawAutoResolve) : null;

	// Client configuration
	const cc = r.clientConfiguration;
	const clientConfig: ClientConfiguration = cc
		? {
				audio: {
					enabled: cc.audio?.enabled ?? true,
					sound: cc.audio?.sound ?? "alarm-default",
					customSoundId: cc.audio?.customSoundId ?? null,
					ascending: cc.audio?.ascending ?? false,
					startVolume: cc.audio?.startVolume ?? 50,
					maxVolume: cc.audio?.maxVolume ?? 80,
					ascendDurationSeconds: cc.audio?.ascendDurationSeconds ?? 30,
					repeatCount: cc.audio?.repeatCount ?? 2,
				},
				visual: {
					flashEnabled: cc.visual?.flashEnabled ?? false,
					flashColor: cc.visual?.flashColor ?? "#ff0000",
					persistentBanner: cc.visual?.persistentBanner ?? true,
					wakeScreen: cc.visual?.wakeScreen ?? false,
				},
				snooze: {
					defaultMinutes: cc.snooze?.defaultMinutes ?? 15,
					options: cc.snooze?.options ?? [5, 15, 30, 60],
					maxCount: cc.snooze?.maxCount ?? 5,
					smartSnooze: cc.snooze?.smartSnooze ?? false,
					smartSnoozeExtendMinutes: cc.snooze?.smartSnoozeExtendMinutes ?? 10,
					conditions: parseSnoozeConditions(cc.snooze),
				},
			}
		: defaultClientConfig();

	// Channels (flat per-rule)
	const channels: ChannelDef[] =
		(r.channels ?? [])
			.slice()
			.sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0))
			.map((c) => ({
				_uid: newUid(),
				channelType: c.channelType ?? ChannelType.WebPush,
				destination: c.destination ?? "",
				destinationLabel: c.destinationLabel ?? "",
			}));

	return {
		name: r.name ?? "",
		description: r.description ?? "",
		severity: (r.severity as AlertRuleSeverity) ?? AlertRuleSeverity.Warning,
		isEnabled: r.isEnabled ?? true,
		sortOrder: r.sortOrder ?? 0,
		condition,
		autoResolveEnabled: r.autoResolveEnabled ?? false,
		autoResolveCondition,
		clientConfig,
		channels: channels.length > 0 ? channels : defaultChannels(),
		allowThroughDnd: r.allowThroughDnd ?? false,
	};
}
